version = 0.1
[default.deploy.parameters]
stack_name = "postman-api-test"
resolve_s3 = true
s3_prefix = "postman-api-test"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
